name: DeathSwapPlugin
version: '${project.version}'
main: me.collebol.deathswapplugin.DeathSwapPlugin
api-version: 1.19
authors: [ ColleBol ]
commands:
  join:
    description: join the game!
  open:
    description: open the game!
  start:
    description: start the game!
  tpalltospawn:
    description: tp allemaal naar de lobby!
